name: CI

on:
  workflow_dispatch:
  push:
      branches: [develop]
  pull_request:
      branches: [develop]

jobs:
  build:
    strategy:
      matrix:
        include:
          - xcode: "15.2"
            deployment_target: ""
    runs-on:  macos-13
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: ./other/download_libs.sh

      - name: Build
        run: xcodebuild -project iina.xcodeproj ONLY_ACTIVE_ARCH=NO -scheme iina -configuration Release ${{ matrix.deployment_target }}
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

      - name: Archive
        run: cd /Users/runner/Library/Developer/Xcode/DerivedData/iina-csbkugdtxazzqogjnydbothqrvib/Build/Products/Release/ && zip -vr ~/iina.zip IINA.app 

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: IINA
          path: ~/iina.zip

